name: Generate Tetris Graph

on:
  schedule:
    - cron: "0 0 * * *" # Se ejecuta cada medianoche
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate Tetris Animation
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.repository_owner }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          filename: github-tetris.svg

      # Forzar que use Node20 si el runner se queja del entorno Docker
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git add github-tetris.svg
          git commit -m "Update Tetris graph" || echo "No changes to commit"
          git push
